newrelic:
  license: '' # New Relic license key

# Iron.io credentials (where you launch your agent)
iron:
  project_id: ''
  token: ''

# Airbreak configuration
airbrake:
  subdomain: ''
  token: ''
